# Nota: Esto asume que el operador de Strimzi ya está instalado en el cluster
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: proyecto3-202200129
spec:
  kafka:
    version: 3.5.1
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.5"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: weather-tweets
  namespace: proyecto3-202200129
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 86400000  # 24 horas
    segment.bytes: 1073741824
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: proyecto3-202200129
spec:
  ports:
  - port: 9092
    name: kafka
    targetPort: 9092
  selector:
    strimzi.io/name: kafka-cluster-kafka