#!/bin/bash
# GUÍA RÁPIDA - Proyecto 3 SOPES
# Carnet: 202200129 | Municipio: Chinautla

clear

echo "╔════════════════════════════════════════════════════════════════════════╗"
echo "║                                                                        ║"
echo "║         🚀 GUÍA RÁPIDA - SISTEMA DE TWEETS DEL CLIMA 🌤️               ║"
echo "║                                                                        ║"
echo "║                     Carnet: 202200129 - Chinautla                     ║"
echo "║                      Universidad USAC - Año 2025                      ║"
echo "║                                                                        ║"
echo "╚════════════════════════════════════════════════════════════════════════╝"
echo ""

# Colores
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
NC='\033[0m'

echo -e "${BLUE}════════════════════════════════════════════════════════════════════════${NC}"
echo -e "${MAGENTA}PASO 0: VERIFICAR CONEXIÓN CON GKE${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════════════════════${NC}"
echo ""
echo "Ya tienes kubeconfig cargado. Verifica con:"
echo ""
echo "  kubectl get nodes"
echo ""
echo "Deberías ver los nodos del cluster: proyecto3-sopes-1"
echo ""

# Verificar conexión
if kubectl get nodes &> /dev/null; then
    echo -e "${GREEN}✓ Conexión con cluster verificada${NC}"
else
    echo -e "${YELLOW}⚠️  No hay conexión con el cluster${NC}"
fi

echo ""
echo -e "${BLUE}════════════════════════════════════════════════════════════════════════${NC}"
echo -e "${MAGENTA}PASO 1: DESPLEGAR LA INFRAESTRUCTURA${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════════════════════${NC}"
echo ""
echo "Primero, actualiza la IP de tu Zot Registry:"
echo ""
echo "  ./update-registry.sh 34.159.50.100:5000"
echo ""
echo "Luego, compila y envía las imágenes Docker:"
echo ""
echo "  ./build-images.sh 34.159.50.100:5000"
echo ""
echo "Finalmente, despliega todo:"
echo ""
echo "  ./deploy.sh"
echo ""
echo -e "${YELLOW}⏱️  Espera 15-20 minutos a que Kafka, RabbitMQ y Valkey estén listos${NC}"
echo ""

echo -e "${BLUE}════════════════════════════════════════════════════════════════════════${NC}"
echo -e "${MAGENTA}PASO 2: MONITOREAR EL DESPLIEGUE${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════════════════════${NC}"
echo ""
echo "En otra terminal, monitorea el progreso:"
echo ""
echo "  kubectl get pods -n weather-system -w"
echo ""
echo "Todos deben estar en estado 'Running' o 'Completed'"
echo ""

echo -e "${BLUE}════════════════════════════════════════════════════════════════════════${NC}"
echo -e "${MAGENTA}PASO 3: EJECUTAR PRUEBAS DE CARGA CON LOCUST${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════════════════════${NC}"
echo ""
echo "Una vez que todos los pods están corriendo:"
echo ""
echo "  ./run-locust.sh"
echo ""
echo "Elige una opción:"
echo "  1 = Modo Web (Interface gráfica - RECOMENDADO)"
echo "  4 = Modo Pesado (10,000 tweets automáticos)"
echo ""

echo -e "${BLUE}════════════════════════════════════════════════════════════════════════${NC}"
echo -e "${MAGENTA}PASO 4: VISUALIZAR EN GRAFANA${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════════════════════${NC}"
echo ""
echo "Mientras Locust genera tweets:"
echo ""
echo "  ./run-grafana.sh"
echo ""
echo "Luego accede a Grafana en:"
echo "  http://localhost:3000"
echo ""
echo "Credenciales:"
echo "  Usuario: admin"
echo "  Contraseña: admin123"
echo ""

echo -e "${BLUE}════════════════════════════════════════════════════════════════════════${NC}"
echo -e "${MAGENTA}PASO 5: VERIFICAR DATOS EN VALKEY${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════════════════════${NC}"
echo ""
echo "Para ver los contadores en tiempo real:"
echo ""
echo "  ./run-valkey.sh"
echo ""
echo "Elige opción 3 para ver contadores o 1 para acceso interactivo"
echo ""

echo -e "${BLUE}════════════════════════════════════════════════════════════════════════${NC}"
echo -e "${MAGENTA}OPCIONES RÁPIDAS${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${GREEN}📊 Ver status general:${NC}"
echo "  ./run-tests.sh"
echo ""
echo -e "${GREEN}🔍 Ver logs en vivo:${NC}"
echo "  kubectl logs -f deployment/go-deployment-1 -n weather-system"
echo ""
echo -e "${GREEN}📈 Ver HPA escalando:${NC}"
echo "  kubectl get hpa -n weather-system -w"
echo ""
echo -e "${GREEN}🧹 Limpiar todo (eliminar namespace):${NC}"
echo "  ./cleanup.sh"
echo ""

echo -e "${BLUE}════════════════════════════════════════════════════════════════════════${NC}"
echo -e "${MAGENTA}INFORMACIÓN IMPORTANTE${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${YELLOW}⚠️  NO HAGAS ESTO ANTES DE LA EVALUACIÓN:${NC}"
echo "  - No destruyas el cluster (debe estar 24+ horas corriendo)"
echo "  - No vacíes Valkey antes de capturar pantallazos"
echo ""
echo -e "${YELLOW}📋 ARCHIVOS IMPORTANTES:${NC}"
echo "  - TECNICA.md: Documentación técnica completa (70+ páginas)"
echo "  - RESUMEN.md: Resumen ejecutivo con checklist"
echo "  - EJEMPLOS.md: Ejemplos de comandos y troubleshooting"
echo "  - README.md: Quick start"
echo ""

echo -e "${BLUE}════════════════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${GREEN}✓ ¡Sistema listo! Comienza con el PASO 0${NC}"
echo ""
