# api-rust-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-rust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-rust
  template:
    metadata:
      labels:
        app: api-rust
    spec:
      containers:
      - name: api-rust
        image: 34.46.81.16:5000/api-rust:latest
        ports:
        - containerPort: 8080
---
# api-rust-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: api-rust
spec:
  selector:
    app: api-rust
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
# api-rust-hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-rust-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-rust
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30
