# kafka-consumer-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - name: kafka-consumer
        image: <your-zot-registry>/kafka-consumer:latest # Replace with your Zot registry path
        env:
        - name: KAFKA_BROKER
          value: "kafka-service:9092"
        - name: VALKEY_ADDR
          value: "valkey-service:6379"
---
# rabbitmq-consumer-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-consumer
  template:
    metadata:
      labels:
        app: rabbitmq-consumer
    spec:
      containers:
      - name: rabbitmq-consumer
        image: <your-zot-registry>/rabbitmq-consumer:latest # Replace with your Zot registry path
        env:
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq-service:5672/"
        - name: VALKEY_ADDR
          value: "valkey-service:6379"
