apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer-deployment
  namespace: proyecto3-202200129
  labels:
    app: kafka-consumer
    student: "202200129"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - name: kafka-consumer
        image: zot-registry:5000/202200129/kafka-consumer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9092
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: KAFKA_BROKERS
          value: "kafka-service:9092"
        - name: KAFKA_TOPIC
          value: "weather-tweets"
        - name: VALKEY_ADDR
          value: "valkey:6379"
        - name: DATA_TTL_HOURS
          value: "24"
        readinessProbe:
          httpGet:
            path: /health
            port: 9092
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 9092
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer-service
  namespace: proyecto3-202200129
spec:
  selector:
    app: kafka-consumer
  ports:
  - port: 9092
    targetPort: 9092
  type: ClusterIP