apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-writer-deployment
  namespace: proyecto3-202200129
  labels:
    app: kafka-writer
    student: "202200129"
spec:
  replicas: 1  # También se probará con 2 réplicas para comparar rendimiento
  selector:
    matchLabels:
      app: kafka-writer
  template:
    metadata:
      labels:
        app: kafka-writer
    spec:
      containers:
      - name: kafka-writer
        image: zot-registry:5000/202200129/kafka-writer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 50051  # Puerto gRPC
        - containerPort: 9090   # Puerto para métricas Prometheus
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: KAFKA_BROKERS
          value: "kafka-service:9092"
        - name: KAFKA_TOPIC
          value: "weather-tweets"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-writer
  namespace: proyecto3-202200129
spec:
  selector:
    app: kafka-writer
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  - name: metrics
    port: 9090
    targetPort: 9090
  type: ClusterIP