apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api-deployment
  namespace: proyecto3-202200129
  labels:
    app: go-api
    student: "202200129"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
      - name: go-api
        image: zot-registry:5000/202200129/go-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: KAFKA_GRPC_SERVICE_ADDR
          value: "kafka-writer:50051"
        - name: RABBIT_GRPC_SERVICE_ADDR
          value: "rabbit-writer:50052"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: go-service
  namespace: proyecto3-202200129
spec:
  selector:
    app: go-api
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP