apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment-1
  namespace: weather-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-deployment-1
  template:
    metadata:
      labels:
        app: go-deployment-1
    spec:
      containers:
      - name: go-deployment-1
        image: localhost:5000/go-deployment-1:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          name: http
        - containerPort: 50051
          name: grpc
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: VALKEY_HOST
          value: "valkey-0.valkey"
        - name: VALKEY_PORT
          value: "6379"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: go-deployment-1
  namespace: weather-system
spec:
  selector:
    app: go-deployment-1
  ports:
  - port: 8081
    targetPort: 8081
    name: http
  - port: 50051
    targetPort: 50051
    name: grpc
  type: ClusterIP
