apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment-1
  namespace: weather-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-deployment-1
  template:
    metadata:
      labels:
        app: go-deployment-1
    spec:
      containers:
      - name: go-deployment-1
        image: kennethreitz/httpbin:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: VALKEY_HOST
          value: "valkey-0.valkey"
        - name: VALKEY_PORT
          value: "6379"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "150m"
---
apiVersion: v1
kind: Service
metadata:
  name: go-deployment-1
  namespace: weather-system
spec:
  selector:
    app: go-deployment-1
  ports:
  - port: 8081
    targetPort: 80
    name: http
  type: ClusterIP
