apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
  namespace: weather-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - name: consumer
        image: ZOT_REGISTRY/go-kafka-consumer:latest
        imagePullPolicy: Always
        env:
        - name: KAFKA_ADDR
          value: "kafka:9092"
        - name: REDIS_ADDR
          value: "valkey:6379"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-consumer
  namespace: weather-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-consumer
  template:
    metadata:
      labels:
        app: rabbitmq-consumer
    spec:
      containers:
      - name: consumer
        image: ZOT_REGISTRY/go-rabbitmq-consumer:latest
        imagePullPolicy: Always
        env:
        - name: RABBITMQ_ADDR
          value: "amqp://guest:guest@rabbitmq:5672/"
        - name: REDIS_ADDR
          value: "valkey:6379"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
