---
# ============ STRIMZI KAFKA OPERATOR ============
# Strimzi is the official Kubernetes operator for Apache Kafka
# It manages Kafka and Zookeeper internally, as specified in the project requirements

---
# Install Strimzi Operator
# We'll apply this from the official Strimzi Helm chart or manifest
# Run these commands first:
# kubectl create namespace strimzi-system
# kubectl apply -f 'https://strimzi.io/install/latest?namespace=strimzi-system' -n strimzi-system

---
# ============ KAFKA CLUSTER (Strimzi) ============
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: weather-kafka
  namespace: weather-system
spec:
  kafka:
    version: 3.4.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.retention.hours: 24
      auto.create.topics.enable: "true"
    storage:
      type: ephemeral
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1024Mi"
        cpu: "500m"
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "250m"
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: "128Mi"
          cpu: "50m"
        limits:
          memory: "256Mi"
          cpu: "150m"
    userOperator:
      resources:
        requests:
          memory: "128Mi"
          cpu: "50m"
        limits:
          memory: "256Mi"
          cpu: "150m"
---
# ============ KAFKA SERVICE (for external access) ============
apiVersion: v1
kind: Service
metadata:
  name: kafka-bootstrap
  namespace: weather-system
spec:
  selector:
    strimzi.io/cluster: weather-kafka
    strimzi.io/kind: Kafka
    strimzi.io/name: weather-kafka-kafka
  ports:
  - port: 9092
    targetPort: 9092
    name: bootstrap
  type: ClusterIP
