apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weather-ingress
  namespace: weather-system
spec:
  ingressClassName: nginx
  rules:
  - host: weather.local
    http:
      paths:
      - path: /api/tweets
        pathType: Prefix
        backend:
          service:
            name: rust-api
            port:
              number: 8080
      - path: /grafana
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 3000
